title: "Showcase | Code Ninjas Langley"
email: showcase@codeninjaslangley.co.uk
timezone: UTC
baseurl: ""
permalink: "/:categories/:title/"
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
author: CN Admin
paginate: 30
disqus: ''
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  cn_admin:
    name: CN Admin
    display_name: Dojo
    avatar: 'assets/images/sal.png'
    email: admin@codeninjaslangley.co.uk
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: ""
  camp_23:
    name: Camps
    display_name: Dojo Camps
    avatar: 'assets/images/john.png'
    email: camps@codeninjaslangley.co.uk
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."
  ninjas:
    name: Ninjas
    display_name: Ninjas
    avatar: 'assets/images/john.png'
    email: ninjas@codeninjaslangley.co.uk
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives